---
- name: Create groups
  group:
    name: "{{ item.name }}"
    state: present
  loop: "{{ groups_to_create }}"

- name: Remove groups
  group:
    name: "{{ item.name }}"
    state: absent
  loop: "{{ groups_to_remove }}"

- name: Create users
  user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    groups: "{{ item.groups }}"
    state: present
  loop: "{{ users_to_create }}"

- name: Remove users
  user:
    name: "{{ item.name }}"
    state: absent
  loop: "{{ users_to_remove }}"

- name: Add users to groups
  user:
    name: "{{ item.name }}"
    groups: "{{ item.groups }}"
    append: yes
  loop: "{{ users_to_add_to_groups }}"

- name: Remove users from groups
  user:
    name: "{{ item.name }}"
    groups: "{{ item.groups }}"
    state: absent
  loop: "{{ users_to_remove_from_groups }}"

