---
- name: Add users
  hosts: client
  remote_user: rao27
  vars:
     users_to_create:
       - name: user1
         shell: /bin/bash
       - name: user2
         shell: /bin/bash
  tasks:
    - name: Add user
      user:
        name: "{{ item.name }}"
        state: present
        shell: "{{ item.shell | default('/bin/bash') }}"
      loop: "{{ users_to_create }}"
      when: item.name not in existing_users | map(attribute='name') | list

- name: Remove users
  hosts: client
  remote_user: rao27
  tasks:
    - name: Remove user
      user:
        name: "{{ item }}"
        state: absent
      loop: "{{ users_to_remove }}"
      when: item in existing_users | map(attribute='name') | list

- name: Add users to groups
  hosts: client
  remote_user: rao27
  tasks:
    - name: Add user to groups
      user:
        name: "{{ item.user }}"
        groups: "{{ item.groups }}"
        append: yes
      loop: "{{ users_to_groups }}"
      when: item.user in existing_users | map(attribute='name') | list

- name: Remove users from groups
  hosts: client
  remote_user: rao27
  tasks:
    - name: Remove user from groups
      user:
        name: "{{ item.user }}"
        groups: "{{ item.groups }}"
        state: absent
      loop: "{{ users_from_groups }}"
      when: item.user in existing_users | map(attribute='name') | list

