---
- name: Update cache and Install Nginx, Copy HTML page, and restart Nginx
  hosts: client
  remote_user: rao27
  become: yes
  tasks:
    - name: Update cache and Install Nginx
      apt:
        name: nginx
        update_cache: yes
        state: latest
      become: yes

    - name: Copy HTML page to remote host
      copy:
        src: /home/ranjith27/webs.html
        dest: /var/www/html/inde.html
      become: yes

    - name: Ensure Nginx service is running and enabled
      service:
        name: nginx
        state: started
        enabled: yes
      become: yes
